services:
  rabbitmq:
    image: rabbitmq:3.13-management
    networks:
      default:
    ports:
      - "5672:5672"
      - "15672:15672"
  mongo_db:
      image: mongo-express
      restart: unless-stopped
      env_file: ./.env
      networks:
        default:
      environment:
        - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
        - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      ports:
        - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
      volumes:
        - db:/data/db
#  app:
#    depends_on:
#      - rabbitmq
#      - mongo_db
#    build: ./
#    restart: on-failure
#    env_file: ./.env
#    ports:
#      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
#    networks:
#      default:
#    environment:
#      SPRING_APPLICATION_JSON: '{
#            "spring.data.mongodb.uri" : "mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongo_db:$MONGODB_DOCKER_PORT/$MONGODB_DATABASE?authSource=admin"
#          }'
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true

volumes:
   db:

networks:
    default: