spring:
  application:
    name: eventing-switchlist
  mvc:
    converters:
      preferred-json-mapper: gson
softwareAsCraft:
  eventing:
    exchange:
      name: "switchlist.exchange"
    queue:
      name: "switchlist.queue"